<a href="https://colab.research.google.com/github/rajwasyafiq/DAA/blob/main/DAAP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
aList = ["john", 33,"Toronto", True]
print(aList)


['john', 33, 'Toronto', True]


In [3]:
aList = ["Rajwa",2020071046,"Informatika", "DAA","15/09/2020", "UPJ", True]
print(aList)

['Rajwa', 2020071046, 'Informatika', 'DAA', '15/09/2020', 'UPJ', True]


In [1]:
aList = ["Rajwa",2020071046,"Informatika", "DAA","15/09/2020", "UPJ", True]
print(aList)

['Rajwa', 2020071046, 'Informatika', 'DAA', '15/09/2020', 'UPJ', True]


In [4]:
aList = ["Rajwa",2020071046,"Informatika", "DAA","15/09/2020", "UPJ", True]
print(aList[1])

2020071046


In [5]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

'Green'

In [6]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1:3]

['Green', 'Blue']

In [8]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
  print(aColor + " Square")


Red Square
Green Square
Blue Square
Yellow Square


In [16]:
bin_Mahasiswa = ["Rajwa","Informatika", "DAA","15/09/2020", "UPJ"]
for aMahasiswa in bin_Mahasiswa:
   print("UPJ" + aMahasiswa)

UPJRajwa
UPJInformatika
UPJDAA
UPJ15/09/2020
UPJUPJ


In [18]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

bin_colors[2:]

['Blue', 'Yellow']

In [23]:
bin_UPJ = ["Universitas","Pembangunan", "Jaya"]
bin_UPJ

['Universitas', 'Pembangunan', 'Jaya']

In [31]:
tuple = ( 100, (200, 400, 600), 300, (400, 800))
print('Pertama : ', tuple[0])
print('Kedua : ',tuple[1])
print('Ketiga : ', tuple[2])
print('Keempat : ',tuple[3])

Pertama :  100
Kedua :  (200, 400, 600)
Ketiga :  300
Keempat :  (400, 800)


In [33]:
bin_colors={ "manual_color":"Yellow", "approved_color":"Green", "refused_color":"Red"}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [35]:
bin_colors.get('refused_color')

'Red'

In [36]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [75]:
bin_colors={ "Nama":"Rajwa", "NIM": 2020071046 , "Prodi":"Informatika", "Universitas":"Pembangunan Jaya"}
print(bin_colors)

{'Nama': 'Rajwa', 'NIM': 2020071046, 'Prodi': 'Informatika', 'Universitas': 'Pembangunan Jaya'}


In [39]:
green = {'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [40]:
green={'grass','leaves','leaves'}
print(green)

{'leaves', 'grass'}


In [74]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'rose', 'blood', 'leaves'}
print(yellow | red)
print(yellow & red)

{'rose', 'dandelions', 'fire hydrant', 'leaves', 'blood'}
{'fire hydrant', 'leaves'}


In [43]:
import pandas as pd
df=pd.DataFrame([['1','Fares', 32, True], ['2','Elena', 23, False], ['3','Steven', 30, True]])

df.columns=['id','name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   30      True

In [44]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   30

In [45]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [48]:
import pandas as pd
df=pd.DataFrame([['1','Informatika', 50, 30, 20], ['2','Sistem Informasi', 55, 30, 25], ['3','Teknik Sipil', 40, 30, 10]])

df.columns=['no', 'Prodi','Mahasiswa','Laki-Laki','Perempuan']
df

no             Prodi  Mahasiswa  Laki-Laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10

In [49]:
import numpy as np
myMatrix=np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [50]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [67]:
class Stack:
  def __init__(self):
    self.items = []
    def isEmpty(self):
      return self.items==[]
      def push(self,item):
        self.items.append(item)
        def pop(self):
          return self.items.pop()
          def peek(self):
            return self.items[len(self.items)-1]
            def size(self):
              return len(self.items)

stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

print(stack.pop())

AttributeError: ignored

In [73]:
class Queue(object):
  def __init__(self):
  self.items = []
  def isEmpty(self):
    return self.items == []
    def enqueue(self, item):
      self.items.insert(0,item)
      def dequeue(self):
        return self.items.pop()
        def size(self):
          return len(self.items)

queue = Queue()
queue.enqueue('red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())
print(queue.dequeue())
print(queue.dequeue())

IndentationError: ignored